package org.analyse.analysestock.realtimecandidate.enums;

public enum DataQualityFlag {
    NORMAL,
    FLAT_INTRADAY_RANGE,
    MISSING_TAIL_VOLUME_BASELINE,
    MISSING_NON_CRITICAL_FACTOR,
    LOW_SAMPLE_COUNT,
    EXTREME_VOLATILITY,
    LOW_LIQUIDITY,
    MARKET_CONTEXT_MISSING,
    SECTOR_CONTEXT_MISSING,
    EXECUTION_DATA_INCOMPLETE
}
