package org.analyse.analysestock.realtimecandidate.enums;

public enum InvalidReason {
    STOCK_ST,
    DELISTED,
    NEW_STOCK,
    MISSING_1400_PRICE,
    MISSING_1430_PRICE,
    MISSING_DAILY_BAR,
    MISSING_PREVIOUS_CLOSE,
    LOW_DAILY_AMOUNT,
    LOW_TAIL_AMOUNT,
    LOW_AMPLITUDE,
    WEAK_TAIL_MOMENTUM,
    LOW_INTRADAY_POSITION,
    HIGH_INTRADAY_POSITION,
    LIMIT_UP_RISK,
    LIMIT_DOWN_RISK,
    HIGH_VOLATILITY,
    WEAK_MARKET,
    NO_BUY_EXECUTION_DATA,
    NO_SELL_EXECUTION_DATA,
    SAMPLE_TOO_LOW,
    PRICE_INVALID,
    VOLUME_INVALID,
    DATA_QUALITY_ISSUE
}
